### ISSUE TITLE
Request for Feedback: OCI image-spec 1.1.0

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/umoci#487]
OCI is approaching a 1.1.0 release on the image-spec and distribution-spec, so we are reaching out to implementations to see if you have any concerns implementing support for those changes that we should address before a GA release.

A full diff of the changes can be viewed at:

- image-spec: https://github.com/opencontainers/image-spec/compare/v1.0.2...opencontainers:image-spec:main
- distribution-spec: https://github.com/opencontainers/distribution-spec/compare/v1.0.1...main

I'm happy to take feedback here, you can raise an issue in OCI, or respond in our tracking issue at https://github.com/opencontainers/image-spec/issues/1093.

**Comment by rchincha** [comment]
There are at least GC implications.

From code, we build a map of descriptors via reflection. However, the issue is that it is possible to push a Manifest with Subject descriptor which may not exist yet.

**Comment by cyphar** [comment]
Thanks for opening the issue! I suspect the main thing we need to add support for is the new `data` attribute for descriptors. The primary blocker to updating the image-spec to the rcs has been issues with the image-tools validation (it cannot handle any image version other than the one it was compiled for, and I suspect it won't be updated to support 1.1.0 any time soon...).

All of the other major changes regarding artefacts are not something umoci handles today (maybe this is something people will want in the future, but given that ORAS exists, we probably don't want to absorb all of that into umoci -- at best, maybe umoci needs to have some "raw" mode to let you use artefacts). And the distribution-spec stuff doesn't apply to us since we (currently) don't have remote registry support.

**Comment by sudo-bmitch** [comment]
Thanks @cyphar! I'll close this out since you're aware of what we're doing. Feel free to keep the conversation going or reopen if you need it for your own tracking.
