### ISSUE TITLE
OS X Support

### ISSUE THREAD

**Issue by huntc** [opencontainers/umoci#98]
Thanks for providing this project.

Are there plans to support OS X?

**Comment by cyphar** [comment]
I don't have plans to support OS X because I don't have an OS X machine.

If it's possible to extend `pkg/system` to work on OS X, I'd be happy to accept patches to that effect.

**Comment by erikh** [comment]
I can do this work. Please leave this ticket open.

**Comment by cyphar** [comment]
Cheers @erikh.

**Comment by cyphar** [comment]
It will probably overlap with #95 because of the necessary refactoring in tar handling.

**Comment by IronCore864** [comment]
I'm not here to mock; with all due respect, but this ticket was from more than 3 years ago ...

**Comment by erikh** [comment]
sorry, I forgot I volunteered to do this.

Please, someone else take the work up.

**Comment by cyphar** [comment]
@IronCore864 in fairness, I wasn't aware this is something more than one person wanted (given all the other things I'm working on, to say that this is at the bottom of my list of priorities is an understatement). Since I don't own a MacOS machine, I have to work through trial-and-error with Travis in order to see if `umoci` works on MacOS.

All of that said, I gave it a shot in #318. But builds are still failing and it probably doesn't work properly...
